// ============================================================
// CompressKro — Unlock PDF Page Component
// ============================================================

import { useState, useRef } from 'react';
import confetti from 'canvas-confetti';
import { 
  Upload, 
  FileText, 
  RefreshCw,
  Unlock,
  Key,
  ListOrdered,
  Lock
} from 'lucide-react';
import { useToast } from '../../hooks/useToast';
import { StorageService } from '../../services/storage.service';
import { HistoryService } from '../../services/history.service';
import { getFriendlySize } from '../../utils/format';
import { BACKEND_API_URL } from '../../constants';
import { ToolPageLayout } from '../../components/ToolPageLayout';
import type { StepItem, BenefitItem, FAQItem, RelatedToolItem } from '../../components/ToolPageLayout';
import { CompiledOutputView } from '../../components/CompiledOutputView';
import type { PDFFileItem } from '../../types';

export function UnlockPdf() {
  const [unlockFile, setUnlockFile] = useState<PDFFileItem | null>(null);
  const [unlockPassword, setUnlockPassword] = useState<string>('');
  const [isProcessing, setIsProcessing] = useState<boolean>(false);
  const [progressMsg, setProgressMsg] = useState<string>('');

  const [outputUrl, setOutputUrl] = useState<string>('');
  const [outputSize, setOutputSize] = useState<number>(0);
  const [outputName, setOutputName] = useState<string>('');

  const unlockInputRef = useRef<HTMLInputElement>(null);
  const { showSuccess, showError } = useToast();

  const clearOutputs = () => {
    setOutputUrl('');
    setOutputSize(0);
    setOutputName('');
  };

  const executeUnlockPdf = async () => {
    if (!unlockFile) return;
    setIsProcessing(true);
    setProgressMsg('Decrypting PDF document...');

    try {
      const formData = new FormData();
      formData.append('file', unlockFile.blob, unlockFile.name);
      formData.append('password', unlockPassword);

      const res = await fetch(`${BACKEND_API_URL}/unlock-pdf`, {
        method: 'POST',
        body: formData
      });

      if (!res.ok) {
        const errJson = await res.json().catch(() => ({}));
        throw new Error(errJson.error || 'Server unlock failed');
      }

      const blob = await res.blob();
      setOutputUrl(URL.createObjectURL(blob));
      setOutputSize(blob.size);
      setOutputName(`unlocked_${unlockFile.name}`);

      StorageService.updateStats(1, 0);
      HistoryService.addPdfEntry('Unlock PDF', `unlocked_${unlockFile.name}`, blob.size);

      showSuccess('PDF unlocked!', `unlocked_${unlockFile.name} · ${getFriendlySize(blob.size)}`);
      confetti({ particleCount: 65, spread: 50, origin: { y: 0.85 } });
    } catch (err: any) {
      console.warn('Backend PDF unlock failed:', err);
      showError('Unlock failed', err.message || 'Incorrect password or backend processing error.');
    } finally {
      setIsProcessing(false);
      setProgressMsg('');
    }
  };

  const steps: StepItem[] = [
    { step: 1, text: 'Click "Select PDF to Unlock" and upload the protected document.' },
    { step: 2, text: 'Enter the password (if you know it) or leave blank if it is owner-restricted only.' },
    { step: 3, text: 'Click "Process Decryption" to strip password layers and download your unlocked PDF.' }
  ];

  const benefits: BenefitItem[] = [
    { title: 'Remove Restrictions', desc: 'Instantly strip passwords, allowing you to edit, print, copy text, or fill forms.' },
    { title: 'Wide Compatibility', desc: 'Compatible with standard RC4 and AES encrypted files generated by Acrobat, Word, etc.' },
    { title: 'Secure Server Process', desc: 'Encrypted files are decrypted on memory buffer and cleaned permanently from servers.' }
  ];

  const faqs: FAQItem[] = [
    { question: 'Do I need to know the password to unlock the PDF?', answer: 'Yes, if the document has a "user password" restricting opening/viewing, you must provide it. If it only has an "owner password" restricting editing or printing, the system can unlock it automatically without a password.' },
    { question: 'Will unlocking change the formatting or text content?', answer: 'No. Unlocking simply modifies the PDF security metadata. All pages, layout ratios, fonts, and internal structures remain unaltered.' },
    { question: 'Can CompressKro crack forgot user passwords?', answer: 'No. Decrypting a user-locked PDF mathematically requires computing the password. CompressKro does not crack passwords.' },
    { question: 'Is this secure for sensitive documents?', answer: 'Yes, our backend operates strict limits, processes the decryption inside sandboxed temp instances, and removes temp files instantly after transmission.' }
  ];

  const relatedTools: RelatedToolItem[] = [
    { name: 'Lock PDF', desc: 'Add passwords to PDFs.', path: '/lock-pdf', icon: Lock },
    { name: 'Merge PDF', desc: 'Combine multiple PDF files.', path: '/merge-pdf', icon: ListOrdered },
    { name: 'Split PDF', desc: 'Extract pages or split ranges.', path: '/split-pdf', icon: FileText }
  ];

  return (
    <ToolPageLayout
      title="Unlock PDF Online"
      subtitle="Remove password protection, restrictions, and encryption from your PDF."
      breadcrumbName="Unlock PDF"
      seoTitle="Unlock PDF Online Free - Remove PDF Password | CompressKro"
      seoDescription="Unlock PDF documents online for free. Remove password protection, viewing restrictions, and editing lockouts from any PDF file. Safe, fast, and easy."
      canonicalPath="/unlock-pdf"
      steps={steps}
      benefits={benefits}
      faqs={faqs}
      relatedTools={relatedTools}
    >
      <div className="space-y-6">
        {outputUrl ? (
          <CompiledOutputView
            outputUrl={outputUrl}
            outputSize={outputSize}
            outputName={outputName}
            onClear={() => {
              clearOutputs();
              setUnlockFile(null);
              setUnlockPassword('');
            }}
          />
        ) : (
          <div className="p-6 rounded-2xl border border-slate-200 dark:border-slate-800 bg-white/40 dark:bg-slate-900/40 glass-panel space-y-6 shadow-sm">
            <h3 className="text-sm font-bold text-slate-800 dark:text-slate-200 flex items-center gap-2">
              <Unlock className="w-4 h-4 text-emerald-500" />
              <span>Remove PDF Password Protection</span>
            </h3>

            <div className="space-y-4">
              <input 
                type="file" 
                ref={unlockInputRef} 
                onChange={(e) => e.target.files?.[0] && setUnlockFile({ id: 'unlock', name: e.target.files[0].name, size: e.target.files[0].size, blob: e.target.files[0] })} 
                accept="application/pdf" 
                className="hidden" 
              />
              <button
                onClick={() => unlockInputRef.current?.click()}
                className="w-full py-3 rounded-xl border border-dashed border-slate-300 dark:border-slate-700 hover:border-rose-500 bg-white/50 dark:bg-slate-950/20 text-xs font-bold text-slate-700 dark:text-slate-300 flex items-center justify-center gap-2 transition-colors cursor-pointer"
              >
                <Upload className="w-4 h-4 text-rose-500" />
                <span>{unlockFile ? unlockFile.name : 'Select PDF to Unlock'}</span>
              </button>

              {unlockFile && (
                <div>
                  <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 mb-1">
                    Document Password (If required)
                  </label>
                  <div className="relative">
                    <Key className="w-3.5 h-3.5 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
                    <input
                      type="password"
                      value={unlockPassword}
                      onChange={(e) => setUnlockPassword(e.target.value)}
                      placeholder="Password (leave blank if only owner-locked)..."
                      className="w-full pl-9 pr-3 py-2 text-xs rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-950 text-slate-800 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-rose-500/30"
                    />
                  </div>
                </div>
              )}
            </div>

            <button
              onClick={executeUnlockPdf}
              disabled={!unlockFile || isProcessing}
              className="w-full py-3 rounded-xl font-bold text-xs text-white bg-gradient-to-r from-emerald-500 to-teal-650 hover:opacity-90 disabled:opacity-40 transition-all flex items-center justify-center gap-2 shadow-sm cursor-pointer"
            >
              {isProcessing ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Unlock className="w-4 h-4" />}
              <span>{isProcessing ? progressMsg : 'Process Decryption'}</span>
            </button>
          </div>
        )}
      </div>
    </ToolPageLayout>
  );
}
